name: Go CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🛠 Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: 📦 Install dependencies
        run: go mod tidy

      - name: ✅ Run tests
        run: go test -v -cover ./...

      - name: 🚀 Create GitHub Release (optional)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
